spring.application.name=GestionDeCine
spring.datasource.url=
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.main.web-application-type=none